### ISSUE TITLE
Hardcoded pin artifact 

### ISSUE THREAD

**Issue by Jedmeyer** [solid-droid/SLIC#1]
Hey Solid, love the work you did here - very convenient.

I was trying to adapt it for a project I'm working on and I discovered several of the pinMode() calls still have hardcoded **8**'s in them, probably just an artifact from development. I changed the code before trying with a different pin. It operated nominally.

**Comment by solid-droid** [comment]
Thanx Jad, I will update it.

**Comment by alper-github** [comment]
Hey Solid, I think you forgot one hardcoded pin 8 on line 127 which goes as "pinMode(8, INPUT);" while updating.

Here's the link of the line:
https://github.com/solid-droid/SLIC/blob/e99ebec74b092a03ebd484758ca1abd7957044a3/library/SLIC/SLIC.cpp#L127

**Comment by solid-droid** [comment]
fixed
